name: CI Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        HOMEBREW_PACKAGES=(
          sdl
          libvorbis
        )
        brew install ${HOMEBREW_PACKAGES[@]}
        cp -v /usr/local/lib/libSDLmain.a engine/openarena-engine-source-*/code/libs/macosx/libSDLmain.a
        cp -v /usr/local/lib/libSDL-1.2.0.dylib engine/openarena-engine-source-*/code/libs/macosx/libSDL-1.2.0.dylib
    - name: Compile
      run: |
        cd engine/openarena-engine-source-*
        make
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: OpenArena-macOS-x86_64
        path: engine/openarena-engine-source-*/build/release-darwin-x86_64/*.x86_64
